### ISSUE TITLE
error not working

### ISSUE THREAD

**Issue by Benoit1478** [peteoheat/pibooth-neopixel_spi#2]
Hello, i try to install this plugin, but it's not working, i have a error like below

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.0.7
Traceback (most recent call last):
  File "/home/pi/.local/bin/pibooth", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.9/site-packages/pibooth/booth.py", line 462, in main
    plugin_manager.load_all_plugins(config.gettuple('GENERAL', 'plugins', 'path'),
  File "/home/pi/.local/lib/python3.9/site-packages/pibooth/plugins/__init__.py", line 66, in load_all_plugins
    plugin = load_module(path)
  File "/home/pi/.local/lib/python3.9/site-packages/pibooth/utils.py", line 276, in load_module
    return loader.load_module(modname)
  File "<frozen importlib._bootstrap_external>", line 469, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 969, in load_module
  File "<frozen importlib._bootstrap_external>", line 794, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/benoit/plugin/pibooth_neopixel_spi.py", line 9
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
pi@PHOTOBOOX-PI1:~ $

**Comment by peteoheat** [comment]
I think you have your _ and your - wrong in your config. The module is called pibooth-neopixel_spi.py. You seem to be referencing pibooth_neopixel_spi.py which is the wrong filename.

**Comment by peteoheat** [comment]
Try with the latest version
